In [20]:
import pandas as pd
import pypsa

### Initialise network
n = pypsa.Network("../networks/isp24_v5_12h.nc")
n.optimize.create_model()

WARNING:pypsa.network.io:Importing network from PyPSA version v0.0.0 while current version is v0.35.2. Read the release notes at https://pypsa.readthedocs.io/en/latest/release_notes.html to prepare your network for import.
INFO:pypsa.network.io:Imported network '12h' has buses, carriers, generators, links, loads, storage_units, transformers

Linopy LP model
===============

Variables:
----------
 * Generator-p_nom (Generator-ext)
 * StorageUnit-p_nom (StorageUnit-ext)
 * Generator-p (snapshot, period, timestep, Generator)
 * Transformer-s (snapshot, period, timestep, Transformer)
 * Link-p (snapshot, period, timestep, Link)
 * StorageUnit-p_dispatch (snapshot, period, timestep, StorageUnit)
 * StorageUnit-p_store (snapshot, period, timestep, StorageUnit)
 * StorageUnit-state_of_charge (snapshot, period, timestep, StorageUnit)

Constraints:
------------
 * Generator-ext-p_nom-lower (Generator-ext)
 * Generator-ext-p_nom-upper (Generator-ext)
 * StorageUnit-ext-p_nom-lower (StorageUnit-ext)
 * StorageUnit-ext-p_nom-upper (StorageUnit-ext)
 * Generator-fix-p-lower (snapshot, period, timestep, Generator-fix)
 * Generator-fix-p-upper (snapshot, period, timestep, Generator-fix)
 * Generator-ext-p-lower (snapshot, period, timestep, Generator-ext)
 * Generator-ext-p-upper (snapshot, period, timestep, Generator-ext)
 * Transformer-fix-s-lower (snapshot, period, timestep, Transformer-fix)
 * Transformer-fix-s-upper (snapshot, period, timestep, Transformer-fix)
 * Link-fix-p-lower (snapshot, period, timestep, Link-fix)
 * Link-fix-p-upper (snapshot, period, timestep, Link-fix)
 * StorageUnit-fix-p_dispatch-lower (snapshot, period, timestep, StorageUnit-fix)
 * StorageUnit-fix-p_dispatch-upper (snapshot, period, timestep, StorageUnit-fix)
 * StorageUnit-ext-p_dispatch-lower (snapshot, period, timestep, StorageUnit-ext)
 * StorageUnit-ext-p_dispatch-upper (snapshot, period, timestep, StorageUnit-ext)
 * StorageUnit-fix-p_store-lower (snapshot, period, timestep, StorageUnit-fix)
 * StorageUnit-fix-p_store-upper (snapshot, period, timestep, StorageUnit-fix)
 * StorageUnit-ext-p_store-lower (snapshot, period, timestep, StorageUnit-ext)
 * StorageUnit-ext-p_store-upper (snapshot, period, timestep, StorageUnit-ext)
 * StorageUnit-fix-state_of_charge-lower (snapshot, period, timestep, StorageUnit-fix)
 * StorageUnit-fix-state_of_charge-upper (snapshot, period, timestep, StorageUnit-fix)
 * StorageUnit-ext-state_of_charge-lower (snapshot, period, timestep, StorageUnit-ext)
 * StorageUnit-ext-state_of_charge-upper (snapshot, period, timestep, StorageUnit-ext)
 * Bus-nodal_balance (Bus, snapshot, period, timestep)
 * Bus-meshed-nodal_balance (Bus-meshed, snapshot, period, timestep)
 * Kirchhoff-Voltage-Law (snapshot, period, timestep, cycles)
 * StorageUnit-energy_balance (snapshot, period, timestep, StorageUnit)

Status:
-------
initialized

# Transmission

In [8]:
n.model.variables["Link-p"]

Variable (snapshot (period, timestep): 5844, Link: 14)
------------------------------------------------------
[(2024, 2024-07-01 00:00:00), CQ-NQ]: Link-p[(2024, 2024-07-01 00:00:00), CQ-NQ] ∈ [-inf, inf]
[(2024, 2024-07-01 00:00:00), CQ-GG]: Link-p[(2024, 2024-07-01 00:00:00), CQ-GG] ∈ [-inf, inf]
[(2024, 2024-07-01 00:00:00), SQ-CQ]: Link-p[(2024, 2024-07-01 00:00:00), SQ-CQ] ∈ [-inf, inf]
[(2024, 2024-07-01 00:00:00), NNSW-SQ QNI]: Link-p[(2024, 2024-07-01 00:00:00), NNSW-SQ QNI] ∈ [-inf, inf]
[(2024, 2024-07-01 00:00:00), NNSW-SQ Terranora]: Link-p[(2024, 2024-07-01 00:00:00), NNSW-SQ Terranora] ∈ [-inf, inf]
[(2024, 2024-07-01 00:00:00), CNSW–NNSW QNI]: Link-p[(2024, 2024-07-01 00:00:00), CNSW–NNSW QNI] ∈ [-inf, inf]
[(2024, 2024-07-01 00:00:00), CNSW­–SNW North]: Link-p[(2024, 2024-07-01 00:00:00), CNSW­–SNW North] ∈ [-inf, inf]
		...
[(2032, 2032-06-30 12:00:00), CNSW–SNW South]: Link-p[(2032, 2032-06-30 12:00:00), CNSW–SNW South] ∈ [-inf, inf]
[(2032, 2032-06-30 12:00:00), SNSW–CNSW VNI]: Link-p[(2032, 2032-06-30 12:00:00), SNSW–CNSW VNI] ∈ [-inf, inf]
[(2032, 2032-06-30 12:00:00), VIC–SNSW VNI]: Link-p[(2032, 2032-06-30 12:00:00), VIC–SNSW VNI] ∈ [-inf, inf]
[(2032, 2032-06-30 12:00:00), VIC-SESA Heywood]: Link-p[(2032, 2032-06-30 12:00:00), VIC-SESA Heywood] ∈ [-inf, inf]
[(2032, 2032-06-30 12:00:00), SESA-CSA]: Link-p[(2032, 2032-06-30 12:00:00), SESA-CSA] ∈ [-inf, inf]
[(2032, 2032-06-30 12:00:00), VIC-CSA Murraylink]: Link-p[(2032, 2032-06-30 12:00:00), VIC-CSA Murraylink] ∈ [-inf, inf]
[(2032, 2032-06-30 12:00:00), TAS-VIC Basslink]: Link-p[(2032, 2032-06-30 12:00:00), TAS-VIC Basslink] ∈ [-inf, inf]

In [21]:
n.model.remove_constraints(["Link-fix-p-lower","Link-fix-p-upper"])

In [2]:
# Maybe just grab costs from PLEXOS model!!!

# Can give an example for how you got the linearised cost for one

import pandas as pd

In [24]:
n.generators

,bus,control,type,p_nom,p_nom_mod,p_nom_extendable,p_nom_min,p_nom_max,p_min_pu,p_max_pu,...,min_up_time,min_down_time,up_time_before,down_time_before,ramp_limit_up,ramp_limit_down,ramp_limit_start_up,ramp_limit_shut_down,weight,p_nom_opt
Generator,,,,,,,,,,,,,,,,,,,,,
Bayswater (BW01),CNSW,PQ,,660.0,0.0,False,0.0,inf,0.0,1.0,...,0,0,1,0,NaN,NaN,1.0,1.0,1.0,0.0
Bayswater (BW02),CNSW,PQ,,685.0,0.0,False,0.0,inf,0.0,1.0,...,0,0,1,0,NaN,NaN,1.0,1.0,1.0,0.0
Bayswater (BW03),CNSW,PQ,,685.0,0.0,False,0.0,inf,0.0,1.0,...,0,0,1,0,NaN,NaN,1.0,1.0,1.0,0.0
Bayswater (BW04),CNSW,PQ,,685.0,0.0,False,0.0,inf,0.0,1.0,...,0,0,1,0,NaN,NaN,1.0,1.0,1.0,0.0
Callide B (CALL_B_1),CQ,PQ,,350.0,0.0,False,0.0,inf,0.0,1.0,...,0,0,1,0,NaN,NaN,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wind_-_offshore_(floating)_VIC_Gippsland_Coast,VIC,PQ,,0.0,0.0,True,0.0,inf,0.0,1.0,...,0,0,1,0,NaN,NaN,1.0,1.0,1.0,0.0
Wind_-_offshore_(floating)_VIC_Portland_Coast,VIC,PQ,,0.0,0.0,True,0.0,inf,0.0,1.0,...,0,0,1,0,NaN,NaN,1.0,1.0,1.0,0.0
Wind_-_offshore_(floating)_SESA_South_East_SA_Coast,SESA,PQ,,0.0,0.0,True,0.0,inf,0.0,1.0,...,0,0,1,0,NaN,NaN,1.0,1.0,1.0,0.0
Wind_-_offshore_(floating)_TAS_North_West_Tasmania_Coast,TAS,PQ,,0.0,0.0,True,0.0,inf,0.0,1.0,...,0,0,1,0,NaN,NaN,1.0,1.0,1.0,0.0
Wind_-_offshore_(floating)_TAS_North_East_Tasmania_Coast,TAS,PQ,,0.0,0.0,True,0.0,inf,0.0,1.0,...,0,0,1,0,NaN,NaN,1.0,1.0,1.0,0.0

In [46]:
bogong = n.model.variables["Generator-p"].loc[(2024,'2024-07-01 00:00:00'):(2025,'2025-06-30 23:30:00'),"Bogong / Mackay (BOGONG1)"]

In [53]:
import numpy as np
x = np.arange(1,731,1)

In [71]:
# bogong
bogong = n.model.variables["Generator-p"].loc[2024,"Bogong / Mackay (BOGONG1)":"Bogong / Mackay (BOGONG2)":]

In [72]:
bogong

Variable (timestep: 368, Generator: 2)
--------------------------------------
[2024-07-01 00:00:00, Bogong / Mackay (BOGONG1)]: Generator-p[(2024, 2024-07-01 00:00:00), Bogong / Mackay (BOGONG1)] ∈ [-inf, inf]
[2024-07-01 00:00:00, Bogong / Mackay (BOGONG2)]: Generator-p[(2024, 2024-07-01 00:00:00), Bogong / Mackay (BOGONG2)] ∈ [-inf, inf]
[2024-07-01 12:00:00, Bogong / Mackay (BOGONG1)]: Generator-p[(2024, 2024-07-01 12:00:00), Bogong / Mackay (BOGONG1)] ∈ [-inf, inf]
[2024-07-01 12:00:00, Bogong / Mackay (BOGONG2)]: Generator-p[(2024, 2024-07-01 12:00:00), Bogong / Mackay (BOGONG2)] ∈ [-inf, inf]
[2024-07-02 00:00:00, Bogong / Mackay (BOGONG1)]: Generator-p[(2024, 2024-07-02 00:00:00), Bogong / Mackay (BOGONG1)] ∈ [-inf, inf]
[2024-07-02 00:00:00, Bogong / Mackay (BOGONG2)]: Generator-p[(2024, 2024-07-02 00:00:00), Bogong / Mackay (BOGONG2)] ∈ [-inf, inf]
[2024-07-02 12:00:00, Bogong / Mackay (BOGONG1)]: Generator-p[(2024, 2024-07-02 12:00:00), Bogong / Mackay (BOGONG1)] ∈ [-inf, inf]
		...
[2024-12-30 00:00:00, Bogong / Mackay (BOGONG2)]: Generator-p[(2024, 2024-12-30 00:00:00), Bogong / Mackay (BOGONG2)] ∈ [-inf, inf]
[2024-12-30 12:00:00, Bogong / Mackay (BOGONG1)]: Generator-p[(2024, 2024-12-30 12:00:00), Bogong / Mackay (BOGONG1)] ∈ [-inf, inf]
[2024-12-30 12:00:00, Bogong / Mackay (BOGONG2)]: Generator-p[(2024, 2024-12-30 12:00:00), Bogong / Mackay (BOGONG2)] ∈ [-inf, inf]
[2024-12-31 00:00:00, Bogong / Mackay (BOGONG1)]: Generator-p[(2024, 2024-12-31 00:00:00), Bogong / Mackay (BOGONG1)] ∈ [-inf, inf]
[2024-12-31 00:00:00, Bogong / Mackay (BOGONG2)]: Generator-p[(2024, 2024-12-31 00:00:00), Bogong / Mackay (BOGONG2)] ∈ [-inf, inf]
[2024-12-31 12:00:00, Bogong / Mackay (BOGONG1)]: Generator-p[(2024, 2024-12-31 12:00:00), Bogong / Mackay (BOGONG1)] ∈ [-inf, inf]
[2024-12-31 12:00:00, Bogong / Mackay (BOGONG2)]: Generator-p[(2024, 2024-12-31 12:00:00), Bogong / Mackay (BOGONG2)] ∈ [-inf, inf]

In [61]:
ws = n.snapshot_weightings.loc[2024,"generators"]

In [62]:
n.model.linexpr((ws,bogong))

LinearExpression [timestep: 368]:
---------------------------------
[2024-07-01 00:00:00]: +1 Generator-p[(2024, 2024-07-01 00:00:00), Bogong / Mackay (BOGONG1)]
[2024-07-01 12:00:00]: +1 Generator-p[(2024, 2024-07-01 12:00:00), Bogong / Mackay (BOGONG1)]
[2024-07-02 00:00:00]: +1 Generator-p[(2024, 2024-07-02 00:00:00), Bogong / Mackay (BOGONG1)]
[2024-07-02 12:00:00]: +1 Generator-p[(2024, 2024-07-02 12:00:00), Bogong / Mackay (BOGONG1)]
[2024-07-03 00:00:00]: +1 Generator-p[(2024, 2024-07-03 00:00:00), Bogong / Mackay (BOGONG1)]
[2024-07-03 12:00:00]: +1 Generator-p[(2024, 2024-07-03 12:00:00), Bogong / Mackay (BOGONG1)]
[2024-07-04 00:00:00]: +1 Generator-p[(2024, 2024-07-04 00:00:00), Bogong / Mackay (BOGONG1)]
		...
[2024-12-28 12:00:00]: +1 Generator-p[(2024, 2024-12-28 12:00:00), Bogong / Mackay (BOGONG1)]
[2024-12-29 00:00:00]: +1 Generator-p[(2024, 2024-12-29 00:00:00), Bogong / Mackay (BOGONG1)]
[2024-12-29 12:00:00]: +1 Generator-p[(2024, 2024-12-29 12:00:00), Bogong / Mackay (BOGONG1)]
[2024-12-30 00:00:00]: +1 Generator-p[(2024, 2024-12-30 00:00:00), Bogong / Mackay (BOGONG1)]
[2024-12-30 12:00:00]: +1 Generator-p[(2024, 2024-12-30 12:00:00), Bogong / Mackay (BOGONG1)]
[2024-12-31 00:00:00]: +1 Generator-p[(2024, 2024-12-31 00:00:00), Bogong / Mackay (BOGONG1)]
[2024-12-31 12:00:00]: +1 Generator-p[(2024, 2024-12-31 12:00:00), Bogong / Mackay (BOGONG1)]

In [ ]:
df = pd.read_csv("../Traces/SC/hydro/MaxEnergyYear_LT_RefYear4006_StepChange.csv",index_col=0)

df.columns = df.columns.str.replace(" Constraint","").str.replace("HT Annual Storage","Annual").str.replace("Bogong - Mackay","Bogong / Mackay")

hydro_gens = pd.read_csv("../isp_sheets_23/hydro/generators.csv",index_col=0).index.to_list()

for hydro in hydro_gens:

    for year in range(2024,2053):
        hydro_var = n.model.variables["Generator-p"].loc[year,hydro]

        upper = df.loc[year,:]
        if year == 2024 or year == 2053:
            upper /= 2

    ws = n.snapshot_weightings.loc[year,"generators"]

    expr = n.model.linexpr((ws,hydro_var))

    n.model.add_constraints(
        expr <= upper, name =f"{hydro} Hydro Max Energy Constraint"
    )

# group generators by hydro

,Barron Gorge,Blowering,Bogong / Mackay,Dartmouth,Eildon,Guthega,Annual,Hume Dam NSW,Hume Dam VIC,Kareeya,West Kiewa
Year,,,,,,,,,,,
2024,76.765777,204.149990,179.232144,54.650574,92.214543,128.509146,3326.378412,98.054393,98.054393,108.347894,74.574966
2025,165.036372,161.178657,173.545856,489.238856,88.828545,128.893313,3449.543982,84.604226,84.604226,144.153224,68.681929
2026,80.946423,94.393911,182.266418,279.172073,49.974270,128.826065,3875.670486,53.806555,53.806555,79.947431,70.752128
2027,93.564750,142.456262,187.077939,40.252678,54.050730,148.975998,3164.927881,70.477255,70.477255,138.805065,58.084630
2028,114.970366,308.844114,230.671803,52.643658,43.127149,174.178592,3694.316271,96.138452,96.138452,117.740196,69.006559
2029,76.765777,200.656530,176.165084,53.715382,90.636548,126.310069,3302.678169,96.376464,96.376464,108.347894,73.298822
2030,119.485510,114.745512,29.588700,387.805282,22.879521,63.661173,2190.869147,25.410942,25.410942,160.252279,30.057156
2031,130.443740,109.866777,262.051950,20.324772,16.465468,167.152046,4442.590043,118.360270,118.360270,169.012815,107.825029
2032,136.550770,254.137790,204.759514,28.111334,96.262105,136.463214,3682.124635,129.897275,129.897275,112.112335,78.951185
2033,91.721262,346.064530,176.209724,169.601697,128.884794,121.905594,2552.866709,110.902823,110.902823,122.391665,55.612254
2034,102.620990,238.122843,214.540083,341.463383,88.809900,152.286367,4625.079027,112.877250,112.877250,150.416436,52.472104
2035,88.050845,149.219607,157.564021,432.332030,95.169219,139.682381,2995.382709,100.580650,100.580650,111.875902,56.386156
2036,54.541790,99.797992,156.882620,490.599527,73.964728,125.210856,3630.875540,87.032975,87.032975,72.697192,62.525217
2037,63.831038,245.333411,249.627835,42.453487,50.023553,164.821517,4055.737768,120.975918,120.975918,117.695156,94.358886
2038,76.765777,200.780412,176.273845,53.748545,90.692505,126.388050,3328.517608,96.435965,96.435965,108.347894,73.344076
2039,165.036372,159.073626,171.279307,482.849283,87.668423,127.209937,3459.669728,83.499275,83.499275,144.153224,67.784927
2040,80.946423,93.488549,180.518243,276.494445,49.494951,127.590453,3895.956616,53.290480,53.290480,79.947431,70.073522
2041,93.564750,141.587505,185.937060,40.007201,53.721106,148.067481,3188.790305,70.047456,70.047456,138.805065,57.730406
2042,114.970366,308.046905,230.076378,52.507771,43.015826,173.728990,3730.711447,95.890293,95.890293,117.740196,68.828435
2043,76.765777,200.849235,176.334268,53.766968,90.723593,126.431374,3342.872851,96.469022,96.469022,108.347894,73.369217
2044,119.485510,114.855704,29.617114,388.177695,22.901493,63.722308,2217.509589,25.435344,25.435344,160.252279,30.086020
2045,130.443740,109.972276,262.303583,20.344289,16.481279,167.312553,4496.563989,118.473924,118.473924,169.012815,107.928567
2046,136.550770,254.381807,204.956120,28.138325,96.354534,136.594243,3726.820742,130.021999,130.021999,112.112335,79.026992
2047,91.721262,346.396790,176.378905,169.764534,129.008538,122.022637,2583.828278,111.009302,111.009302,122.391665,55.665648
2048,102.620990,238.351451,214.746051,341.791204,88.895162,152.432569,4681.124162,112.985617,112.985617,150.416436,52.522480
2049,88.050845,149.362854,157.715280,432.747060,95.260579,139.816474,3031.648349,100.677205,100.677205,111.875902,56.440285
2050,54.541790,99.442434,156.323683,488.851633,73.701209,124.764758,3670.972756,86.722896,86.722896,72.697192,62.302454
2051,63.831038,243.349914,247.609617,42.110254,49.619117,163.488951,4095.566676,119.997839,119.997839,117.695156,93.596003
2052,76.765777,198.249290,174.051664,53.070968,89.549197,124.794750,3357.141124,95.220253,95.220253,108.347894,72.419470
2053,165.036372,156.349122,168.345753,474.579374,86.166899,125.031173,3485.204431,82.069157,82.069157,144.153224,66.623954

In [69]:
df['Fuel type'].unique()

array(['Black Coal', 'Brown Coal', 'Gas', 'Liquid Fuel', 'Water', 'Solar',
       'Wind'], dtype=object)

In [70]:
# policy is easy

# combine a sheet into 'all'
df = pd.read_csv("../isp_sheets_23/summary_mapping/existing.csv",index_col=0)
# df = pd.read_csv("../isp_sheets_23/summary_mapping/all.csv",index_col=0)
# df = pd.read_csv("../isp_sheets_23/seasonal_ratings/existing_gen_seasonal_ratings.csv",index_col=0)
# df = pd.read_csv("../isp_sheets_23/seasonal_ratings/all.csv",index_col=0)

df['Fuel type'].unique()
df['Region'].unique()

for region in df['Region'].unique():
        
    df_r = df[(df['Region']==region)]

    # for fueltype in df['Fuel type'].unique():

    df_thermal = df_r[df_r['Fuel type'].isin(['Black Coal','Brown Coal','Gas','Liquid Fuel'])]
    df_vre     = df_r[df_r['Fuel type'].isin(['Water','Solar','Wind'])]

    # df_temp = df[(df['Fuel type']==region) & ]

    print(df_thermal)

# n.generators

                               Technology type Region Sub-region REZ location  \
Existing generator
Bayswater                   Steam Sub Critical    NSW       CNSW          NaN
Eraring                     Steam Sub Critical    NSW        SNW          NaN
Mt Piper                    Steam Sub Critical    NSW       CNSW          NaN
Vales Point B               Steam Sub Critical    NSW        SNW          NaN
Tallawarra                                CCGT    NSW        SNW          NaN
Colongra                                  OCGT    NSW        SNW          NaN
Smithfield Energy Facility                OCGT    NSW        SNW          NaN
Uranquinty                                OCGT    NSW       SNSW          NaN

                              Status  Regional build cost zone   Fuel type  \
Existing generator
Bayswater                   Existing                       NaN  Black Coal
Eraring                     Existing                       NaN  Black Coal
Mt Piper                    Existing                       NaN  Black Coal
Vales Point B               Existing                       NaN  Black Coal
Tallawarra                  Existing                       NaN         Gas
Colongra                    Existing                       NaN         Gas
Smithfield Energy Facility  Existing                       NaN         Gas
Uranquinty                  Existing                       NaN         Gas

                                     Fuel cost mapping  \
Existing generator
Bayswater                                    Bayswater
Eraring                                        Eraring
Mt Piper                                      Mt Piper
Vales Point B                            Vales Point B
Tallawarra                                  Tallawarra
Colongra                                      Colongra
Smithfield Energy Facility  Smithfield Energy Facility
Uranquinty                                  Uranquinty

                                    Summer rating (MW)  \
Existing generator
Bayswater                                    Bayswater
Eraring                                        Eraring
Mt Piper                                      Mt Piper
Vales Point B                            Vales Point B
Tallawarra                                  Tallawarra
Colongra                                      Colongra
Smithfield Energy Facility  Smithfield Energy Facility
Uranquinty                                  Uranquinty

                                    Winter rating (MW)  ...  \
Existing generator                                      ...
Bayswater                                    Bayswater  ...
Eraring                                        Eraring  ...
Mt Piper                                      Mt Piper  ...
Vales Point B                            Vales Point B  ...
Tallawarra                                  Tallawarra  ...
Colongra                                      Colongra  ...
Smithfield Energy Facility  Smithfield Energy Facility  ...
Uranquinty                                  Uranquinty  ...

                           Mean time to repair - Partial outage Until 2022  \
Existing generator
Bayswater                                                   Black Coal NSW
Eraring                                                     Black Coal NSW
Mt Piper                                                    Black Coal NSW
Vales Point B                                               Black Coal NSW
Tallawarra                                            Steam Turbine & CCGT
Colongra                                                        OCGT Small
Smithfield Energy Facility                                      OCGT Small
Uranquinty                                                            OCGT

                           Mean time to repair - Partial outage Post 2022  \
Existing generator
Bayswater                                                  Black Coal NSW
Eraring                                                    Black Coal NSW
Mt Piper                                                   Black Coal NSW
Vales Point B                                              Black Coal NSW
Tallawarra                                           Steam Turbine & CCGT
Colongra                                                       OCGT Small
Smithfield Energy Facility                                     OCGT Small
Uranquinty                                                           OCGT

                           Maintenance duration (%) Minimum load (MW)  \
Existing generator
Bayswater                                Black Coal              BW01
Eraring                                  Black Coal              ER01
Mt Piper                                 Black Coal               MP1
Vales Point B                            Black Coal               VP5
Tallawarra                                     CCGT               NaN
Colongra                                       OCGT               NaN
Smithfield Energy Facility                     OCGT               NaN
Uranquinty                                     OCGT               NaN

                           Maximum capacity factor (%)  \
Existing generator
Bayswater                                     NSW Coal
Eraring                                       NSW Coal
Mt Piper                                      NSW Coal
Vales Point B                                 NSW Coal
Tallawarra                                         NaN
Colongra                                           NaN
Smithfield Energy Facility                         NaN
Uranquinty                                         NaN

                                      FOM ($/kW/annum)  \
Existing generator
Bayswater                                    Bayswater
Eraring                                        Eraring
Mt Piper                                      Mt Piper
Vales Point B                            Vales Point B
Tallawarra                                  Tallawarra
Colongra                                      Colongra
Smithfield Energy Facility  Smithfield Energy Facility
Uranquinty                                  Uranquinty

                                  VOM ($/MWh sent-out)  \
Existing generator
Bayswater                                    Bayswater
Eraring                                        Eraring
Mt Piper                                      Mt Piper
Vales Point B                            Vales Point B
Tallawarra                                  Tallawarra
Colongra                                      Colongra
Smithfield Energy Facility  Smithfield Energy Facility
Uranquinty                                  Uranquinty

                                              Heat rate  \
Existing generator
Bayswater                                     Bayswater
Eraring                                         Eraring
Mt Piper                                       Mt Piper
Vales Point B                             Vales Point B
Tallawarra                                   Tallawarra
Colongra                                       Colongra
Smithfield Energy Facility  Smithfield Energy Facility3
Uranquinty                                   Uranquinty

                                                   MLF Auxiliary load (%)
Existing generator
Bayswater                                    Bayswater     Black Coal NSW
Eraring                                        Eraring     Black Coal NSW
Mt Piper                                      Mt Piper     Black Coal NSW
Vales Point B                            Vales Point B     Black Coal NSW
Tallawarra                                  Tallawarra               CCGT
Colongra                                      Colongra               OCGT
Smithfield Energy Facility  Smithfield Energy Facility               OCGT
Uranquinty                                  Uranquinty               OCGT

[8 rows x 26 columns]
                               Technology type Region Sub-region REZ location  \
Existing generator
Callide B                   Steam Sub Critical    QLD         CQ          NaN
Callide C                 Steam Super Critical    QLD         CQ          NaN
Gladstone                   Steam Sub Critical    QLD         GG          NaN
Kogan Creek               Steam Super Critical    QLD         SQ          NaN
Millmerran                Steam Super Critical    QLD         SQ          NaN
Stanwell                    Steam Sub Critical    QLD         CQ          NaN
Tarong                      Steam Sub Critical    QLD         SQ          NaN
Tarong North              Steam Super Critical    QLD         SQ          NaN
Condamine A                               CCGT    QLD         SQ          NaN
Darling Downs                             CCGT    QLD         SQ          NaN
Swanbank E GT                             CCGT    QLD         SQ          NaN
Townsville Power Station                  CCGT    QLD         NQ          NaN
Yarwun Cogen                              CCGT    QLD         GG          NaN
Barcaldine Power Station                  OCGT    QLD         CQ          NaN
Braemar                                   OCGT    QLD         SQ          NaN
Braemar 2 Power Station                   OCGT    QLD         SQ          NaN
Mt Stuart                                 OCGT    QLD         NQ          NaN
Oakey Power Station                       OCGT    QLD         SQ          NaN
Roma                                      OCGT    QLD         SQ          NaN

                            Status  Regional build cost zone    Fuel type  \
Existing generator
Callide B                 Existing                       NaN   Black Coal
Callide C                 Existing                       NaN   Black Coal
Gladstone                 Existing                       NaN   Black Coal
Kogan Creek               Existing                       NaN   Black Coal
Millmerran                Existing                       NaN   Black Coal
Stanwell                  Existing                       NaN   Black Coal
Tarong                    Existing                       NaN   Black Coal
Tarong North              Existing                       NaN   Black Coal
Condamine A               Existing                       NaN          Gas
Darling Downs             Existing                       NaN          Gas
Swanbank E GT             Existing                       NaN          Gas
Townsville Power Station  Existing                       NaN          Gas
Yarwun Cogen              Existing                       NaN          Gas
Barcaldine Power Station  Existing                       NaN          Gas
Braemar                   Existing                       NaN          Gas
Braemar 2 Power Station   Existing                       NaN          Gas
Mt Stuart                 Existing                       NaN  Liquid Fuel
Oakey Power Station       Existing                       NaN          Gas
Roma                      Existing                       NaN          Gas

                                 Fuel cost mapping        Summer rating (MW)  \
Existing generator
Callide B                                Callide B                 Callide B
Callide C                                Callide C                 Callide C
Gladstone                                Gladstone                 Gladstone
Kogan Creek                            Kogan Creek               Kogan Creek
Millmerran                              Millmerran                Millmerran
Stanwell                                  Stanwell                  Stanwell
Tarong                                      Tarong                    Tarong
Tarong North                          Tarong North              Tarong North
Condamine A                            Condamine A               Condamine A
Darling Downs                        Darling Downs             Darling Downs
Swanbank E GT                        Swanbank E GT             Swanbank E GT
Townsville Power Station  Townsville Power Station  Townsville Power Station
Yarwun Cogen                          Yarwun Cogen              Yarwun Cogen
Barcaldine Power Station  Barcaldine Power Station  Barcaldine Power Station
Braemar                                    Braemar                   Braemar
Braemar 2 Power Station    Braemar 2 Power Station   Braemar 2 Power Station
Mt Stuart                              Liquid Fuel                 Mt Stuart
Oakey Power Station            Oakey Power Station       Oakey Power Station
Roma                                          Roma                      Roma

                                Winter rating (MW)  ...  \
Existing generator                                  ...
Callide B                                Callide B  ...
Callide C                                Callide C  ...
Gladstone                                Gladstone  ...
Kogan Creek                            Kogan Creek  ...
Millmerran                              Millmerran  ...
Stanwell                                  Stanwell  ...
Tarong                                      Tarong  ...
Tarong North                          Tarong North  ...
Condamine A                            Condamine A  ...
Darling Downs                        Darling Downs  ...
Swanbank E GT                        Swanbank E GT  ...
Townsville Power Station  Townsville Power Station  ...
Yarwun Cogen                          Yarwun Cogen  ...
Barcaldine Power Station  Barcaldine Power Station  ...
Braemar                                    Braemar  ...
Braemar 2 Power Station    Braemar 2 Power Station  ...
Mt Stuart                                Mt Stuart  ...
Oakey Power Station            Oakey Power Station  ...
Roma                                          Roma  ...

                         Mean time to repair - Partial outage Until 2022  \
Existing generator
Callide B                                                 Black Coal QLD
Callide C                                                 Black Coal QLD
Gladstone                                                 Black Coal QLD
Kogan Creek                                               Black Coal QLD
Millmerran                                                Black Coal QLD
Stanwell                                                  Black Coal QLD
Tarong                                                    Black Coal QLD
Tarong North                                              Black Coal QLD
Condamine A                                         Steam Turbine & CCGT
Darling Downs                                       Steam Turbine & CCGT
Swanbank E GT                                       Steam Turbine & CCGT
Townsville Power Station                            Steam Turbine & CCGT
Yarwun Cogen                                        Steam Turbine & CCGT
Barcaldine Power Station                                      OCGT Small
Braemar                                                             OCGT
Braemar 2 Power Station                                             OCGT
Mt Stuart                                                     OCGT Small
Oakey Power Station                                                 OCGT
Roma                                                          OCGT Small

                         Mean time to repair - Partial outage Post 2022  \
Existing generator
Callide B                                                Black Coal QLD
Callide C                                                Black Coal QLD
Gladstone                                                Black Coal QLD
Kogan Creek                                              Black Coal QLD
Millmerran                                               Black Coal QLD
Stanwell                                                 Black Coal QLD
Tarong                                                   Black Coal QLD
Tarong North                                             Black Coal QLD
Condamine A                                        Steam Turbine & CCGT
Darling Downs                                      Steam Turbine & CCGT
Swanbank E GT                                      Steam Turbine & CCGT
Townsville Power Station                           Steam Turbine & CCGT
Yarwun Cogen                                       Steam Turbine & CCGT
Barcaldine Power Station                                     OCGT Small
Braemar                                                            OCGT
Braemar 2 Power Station                                            OCGT
Mt Stuart                                                    OCGT Small
Oakey Power Station                                                OCGT
Roma                                                         OCGT Small

                         Maintenance duration (%) Minimum load (MW)  \
Existing generator
Callide B                              Black Coal          CALL_B_1
Callide C                              Black Coal             CPP_3
Gladstone                              Black Coal           GSTONE1
Kogan Creek                            Black Coal             KPP_1
Millmerran                             Black Coal             MPP_1
Stanwell                               Black Coal            STAN-1
Tarong                                 Black Coal          TARONG#1
Tarong North                           Black Coal             TNPS1
Condamine A                                  CCGT               NaN
Darling Downs                                CCGT               NaN
Swanbank E GT                                CCGT               NaN
Townsville Power Station                     CCGT               NaN
Yarwun Cogen                                 CCGT               NaN
Barcaldine Power Station                     OCGT               NaN
Braemar                                      OCGT               NaN
Braemar 2 Power Station                      OCGT               NaN
Mt Stuart                                    OCGT               NaN
Oakey Power Station                          OCGT               NaN
Roma                                         OCGT               NaN

                         Maximum capacity factor (%)  \
Existing generator
Callide B                                        NaN
Callide C                                        NaN
Gladstone                                        NaN
Kogan Creek                                      NaN
Millmerran                                       NaN
Stanwell                                         NaN
Tarong                                           NaN
Tarong North                                     NaN
Condamine A                                      NaN
Darling Downs                                    NaN
Swanbank E GT                                    NaN
Townsville Power Station                         NaN
Yarwun Cogen                                     NaN
Barcaldine Power Station                         NaN
Braemar                                          NaN
Braemar 2 Power Station                          NaN
Mt Stuart                                        NaN
Oakey Power Station                              NaN
Roma                                             NaN

                                  FOM ($/kW/annum)      VOM ($/MWh sent-out)  \
Existing generator
Callide B                                Callide B                 Callide B
Callide C                                Callide C                 Callide C
Gladstone                                Gladstone                 Gladstone
Kogan Creek                            Kogan Creek               Kogan Creek
Millmerran                              Millmerran                Millmerran
Stanwell                                  Stanwell                  Stanwell
Tarong                                      Tarong                    Tarong
Tarong North                          Tarong North              Tarong North
Condamine A                            Condamine A               Condamine A

In [ ]:

df = pd.read_csv("REZ/rez_summary")
# df = pd.read_csv("../isp_sheets_23/summary_mapping/all.csv",index_col=0)

df = pd.read_csv("REZ/single_rez")

gens = network.generators

# group gens by REZ

for _,row in df.iterrows():
    
    "_".join(REZ location)

    groupby REZ location

    apply limits

In [ ]:
def define_nodal_balance_constraints_classic(n, snapshots):
    m = n.model
    buses = n.buses.index

    exprs = []

    # Generators
    if not n.generators.empty:
        exprs.append(
            m["Generator-p"].groupby(n.generators.bus).sum()
        )

    # Stores
    if not n.stores.empty:
        exprs.append(
            m["Store-p"].groupby(n.stores.bus).sum()
        )

    # StorageUnits
    if not n.storage_units.empty:
        exprs.append(
            (m["StorageUnit-p_dispatch"]
             - m["StorageUnit-p_store"]).groupby(n.storage_units.bus).sum()
        )

    # print(exprs)

    # Lines
    if not n.lines.empty:
        exprs.append(
            -m["Line-s"].groupby(n.lines.bus0).sum().rename(bus0="bus")
        )
        exprs.append(
            (m["Line-s"]).groupby(n.lines.bus1).sum().rename(bus1="bus")
        )

    print(exprs)

    # Transformers
    if not n.transformers.empty:
        exprs.append(
            (-m["Transformer-s"]).groupby(n.transformers.bus0).sum().rename(bus0="bus")
        )
        exprs.append(
            (m["Transformer-s"]).groupby(n.transformers.bus1).sum().rename(bus1="bus")
        )

    # Links
    if not n.links.empty:
        exprs.append(
            (-m["Link-p"]).groupby(n.links.bus0).sum()
        )
        exprs.append(
            (m["Link-p"]).groupby(n.links.bus1).sum()
        )
        
    lhs = sum(exprs)

    print(lhs)

    # Prepare RHS (loads)
    loads = getattr(n, "loads", None)
    if loads is None or loads.empty:
        rhs = DataArray(
            0.0,
            coords={"snapshot": sns, "name": buses},
            dims=["snapshot", "name"],
        )
    else:
        loads_values = loads["p_set"].loc[loads.index.unique()]
        load_buses = loads["bus"].loc[loads.index.unique()]
        load_buses = load_buses[load_buses.isin(buses)]
        rhs = (
            loads_values.groupby(load_buses)
            .sum()
            # .rename(Bus="name")
            # .reindex(name=buses, fill_value=0)
        )
    debug_print("Final RHS", rhs)

    # Mask for empty constraints
    empty_nodal_balance = (lhs.vars == -1).all("_term")
    if empty_nodal_balance.any():
        if (empty_nodal_balance & (rhs != 0)).any().item():
            msg = "Empty LHS with non-zero RHS in nodal balance constraint."
            raise ValueError(msg)
        mask = ~empty_nodal_balance
    else:
        mask = None

    # Add constraints
    # n.model.add_constraints(lhs, "=", rhs, name=f"Bus{suffix}-nodal_balance new", mask=mask)

    print(rhs)

    n.model.add_constraints(lhs, "=", rhs, name="Bus-nodal_balance new3")

    return lhs

network.model.remove_constraints('Bus-nodal_balance new3')
    # Assuming you have a network object called 'network' and a snapshot index 'snapshots'
exps = define_nodal_balance_constraints_classic(network,snapshots)

In [4]:
import os

os.listdir("../isp_sheets_23/REZ_augmentation/")

['rez_initial.csv', 'rez_single_aug.csv', 'TODO.txt']

In [6]:
df = pd.read_csv("../isp_sheets_23/REZ_augmentation/rez_initial.csv",index_col=1)

df

                                        REZ  Limit            Day Type
ID
N1               REZLimit_N1_North West NSW    171                 NaN
N10               REZLimit_N10_Hunter Coast   5650                 NaN
N11            REZLimit_N11_Illawarra Coast   1000                 NaN
N2                  REZLimit_N2_New England    577                 NaN
N3           REZLimit_N3_Central-West Orana    900                 NaN
N4                  REZLimit_N4_Broken Hill    250                 NaN
N5               REZLimit_N5_South West NSW    215                 NaN
N6                  REZLimit_N6_Wagga Wagga   1100                 NaN
N8                 REZLimit_N8_Cooma-Monaro    350                 NaN
N9         REZLimit_N9_Hunter-Central Coast    400                 NaN
Q1                REZLimit_Q1_Far North Qld    750                 NaN
Q2   REZLimit_Q2_North Qld Clean Energy Hub    700                 NaN
Q5                   REZLimit_Q5_Barcaldine     85                 NaN
Q9                       REZLimit_Q9_Banana    150                 NaN
S10        REZLimit_S10_South East SA Coast      0                 NaN
S2                    REZLimit_S2_Riverland    130                 NaN
S4              REZLimit_S4_Yorke Peninsula    100                 NaN
S6                  REZLimit_S6_Leigh Creek      0                 NaN
S7                  REZLimit_S7_Roxby Downs    500                 NaN
S8       REZLimit_S8_Eastern Eyre Peninsula    300                 NaN
S9       REZLimit_S9_Western Eyre Peninsula      0                 NaN
T1          REZLimit_T1_North East Tasmania    400                 NaN
V1                 REZLimit_V1_Ovens Murray    350                 NaN
T2          REZLimit_T2_North West Tasmania    277         TAS Hot Day
T2          REZLimit_T2_North West Tasmania    277  TAS Typical Summer
T2          REZLimit_T2_North West Tasmania    112          TAS Winter
T3            REZLimit_T3_Central Highlands    527         TAS Hot Day
T3            REZLimit_T3_Central Highlands    527  TAS Typical Summer
T3            REZLimit_T3_Central Highlands    668          TAS Winter
V2                 REZLimit_V2_Murray River    440         VIC Hot Day
V2                 REZLimit_V2_Murray River    440  VIC Typical Summer
V2                 REZLimit_V2_Murray River    640          VIC Winter
V6            REZLimit_V6_Central North VIC    650         VIC Hot Day
V6            REZLimit_V6_Central North VIC    650  VIC Typical Summer
V6            REZLimit_V6_Central North VIC   1300          VIC Winter

In [3]:
48/8

6.0

In [9]:
508416/48

10592.0

In [7]:
84736*(48/8)

508416.0

In [13]:
n.model.variables["Link-p"].loc[(2024,),"CQ-NQ"]

Variable (timestep: 368)
------------------------
[2024-07-01 00:00:00]: Link-p[(2024, 2024-07-01 00:00:00), CQ-NQ] ∈ [-inf, inf]
[2024-07-01 12:00:00]: Link-p[(2024, 2024-07-01 12:00:00), CQ-NQ] ∈ [-inf, inf]
[2024-07-02 00:00:00]: Link-p[(2024, 2024-07-02 00:00:00), CQ-NQ] ∈ [-inf, inf]
[2024-07-02 12:00:00]: Link-p[(2024, 2024-07-02 12:00:00), CQ-NQ] ∈ [-inf, inf]
[2024-07-03 00:00:00]: Link-p[(2024, 2024-07-03 00:00:00), CQ-NQ] ∈ [-inf, inf]
[2024-07-03 12:00:00]: Link-p[(2024, 2024-07-03 12:00:00), CQ-NQ] ∈ [-inf, inf]
[2024-07-04 00:00:00]: Link-p[(2024, 2024-07-04 00:00:00), CQ-NQ] ∈ [-inf, inf]
		...
[2024-12-28 12:00:00]: Link-p[(2024, 2024-12-28 12:00:00), CQ-NQ] ∈ [-inf, inf]
[2024-12-29 00:00:00]: Link-p[(2024, 2024-12-29 00:00:00), CQ-NQ] ∈ [-inf, inf]
[2024-12-29 12:00:00]: Link-p[(2024, 2024-12-29 12:00:00), CQ-NQ] ∈ [-inf, inf]
[2024-12-30 00:00:00]: Link-p[(2024, 2024-12-30 00:00:00), CQ-NQ] ∈ [-inf, inf]
[2024-12-30 12:00:00]: Link-p[(2024, 2024-12-30 12:00:00), CQ-NQ] ∈ [-inf, inf]
[2024-12-31 00:00:00]: Link-p[(2024, 2024-12-31 00:00:00), CQ-NQ] ∈ [-inf, inf]
[2024-12-31 12:00:00]: Link-p[(2024, 2024-12-31 12:00:00), CQ-NQ] ∈ [-inf, inf]

In [ ]:
# Base flows

df = pd.read_csv("../isp_sheets_23/network_capability/flow_path_capability.csv")

# Add options

expand = pd.read_csv("../isp_sheets_23/network_capability/linearised_costs.csv",index_col=0)

# Committed and anticipated

# VIC-SESA Heywood 100
# SESA-CSA 100
# SNSW-CSA and VIC-SESA combined 650,800
# CNSW - SNW 1160,0 north south combined
# SNSW-CNSW VNI, 250,0
# CNSW-NNSW 0,300

# Pretend these have been added # new constraints just have an increase amount

# SNSW-CSA 800
# TAS-VIC Marinus Link
# SNSW–CNSW Humelink

# Add variables

n.model.add_variables()

# Costs must increase each year 

for _,row in df.iterrows():


    link = row["Plain Name"]


    # only add objective every year BRUH
    for year in n.investment_periods:

        # skip 2024
        if year==2024:
            continue

        # grow by 1% each year

        link_year = n.model.variables["Link-p"].loc[(year,),link]

        if link in expand.index:

            expand_row = expand.loc[link]

            if expand_row["Forward increase"] > 0:

                if year==2025:

                    increase_amount = n.model.add_variables(lower=0,upper=expand_row["Forward increase"],name=f"{link} + forward increase")
                
                else:

                    increase_amount = n.model.variables[f"{link} + forward increase"]

                n.model.add_constraints(link_year <= row["Max forward"] + increase_amount,
                                        name = link + f"-upper-{year}")
                
                n.model.objective += expand.loc[link,"Forward cost"]*(1.001**(year-2024))*increase_amount
                
            if expand_row["Reverse increase"] > 0:

                if year==2025:

                    increase_amount = n.model.add_variables(lower=0,upper=expand_row["Reverse increase"],name=f"{link} + reverse increase")
                
                else:

                    increase_amount = n.model.variables[f"{link} + reverse increase"]

                n.model.add_constraints(-link_year <= row["Max reverse"] + increase_amount,
                                        name = link + f"-lower-{year}")
                
                n.model.objective += expand.loc[link,"Reverse cost"]*(1.001**(year-2024))*increase_amount

In [23]:
n.model.constraints

linopy.model.Constraints
------------------------
 * Generator-ext-p_nom-lower (Generator-ext)
 * Generator-ext-p_nom-upper (Generator-ext)
 * StorageUnit-ext-p_nom-lower (StorageUnit-ext)
 * StorageUnit-ext-p_nom-upper (StorageUnit-ext)
 * Generator-fix-p-lower (snapshot, period, timestep, Generator-fix)
 * Generator-fix-p-upper (snapshot, period, timestep, Generator-fix)
 * Generator-ext-p-lower (snapshot, period, timestep, Generator-ext)
 * Generator-ext-p-upper (snapshot, period, timestep, Generator-ext)
 * Transformer-fix-s-lower (snapshot, period, timestep, Transformer-fix)
 * Transformer-fix-s-upper (snapshot, period, timestep, Transformer-fix)
 * StorageUnit-fix-p_dispatch-lower (snapshot, period, timestep, StorageUnit-fix)
 * StorageUnit-fix-p_dispatch-upper (snapshot, period, timestep, StorageUnit-fix)
 * StorageUnit-ext-p_dispatch-lower (snapshot, period, timestep, StorageUnit-ext)
 * StorageUnit-ext-p_dispatch-upper (snapshot, period, timestep, StorageUnit-ext)
 * StorageUnit-fix-p_store-lower (snapshot, period, timestep, StorageUnit-fix)
 * StorageUnit-fix-p_store-upper (snapshot, period, timestep, StorageUnit-fix)
 * StorageUnit-ext-p_store-lower (snapshot, period, timestep, StorageUnit-ext)
 * StorageUnit-ext-p_store-upper (snapshot, period, timestep, StorageUnit-ext)
 * StorageUnit-fix-state_of_charge-lower (snapshot, period, timestep, StorageUnit-fix)
 * StorageUnit-fix-state_of_charge-upper (snapshot, period, timestep, StorageUnit-fix)
 * StorageUnit-ext-state_of_charge-lower (snapshot, period, timestep, StorageUnit-ext)
 * StorageUnit-ext-state_of_charge-upper (snapshot, period, timestep, StorageUnit-ext)
 * Bus-nodal_balance (Bus, snapshot, period, timestep)
 * Bus-meshed-nodal_balance (Bus-meshed, snapshot, period, timestep)
 * Kirchhoff-Voltage-Law (snapshot, period, timestep, cycles)
 * StorageUnit-energy_balance (snapshot, period, timestep, StorageUnit)
 * CQ-NQ-upper-2025 (Link, period, timestep)
 * CQ-NQ-lower-2025 (Link, period, timestep)
 * CQ-NQ-upper-2026 (Link, period, timestep)
 * CQ-NQ-lower-2026 (Link, period, timestep)
 * CQ-NQ-upper-2027 (Link, period, timestep)
 * CQ-NQ-lower-2027 (Link, period, timestep)
 * CQ-NQ-upper-2028 (Link, period, timestep)
 * CQ-NQ-lower-2028 (Link, period, timestep)
 * CQ-NQ-upper-2029 (Link, period, timestep)
 * CQ-NQ-lower-2029 (Link, period, timestep)
 * CQ-NQ-upper-2030 (Link, period, timestep)
 * CQ-NQ-lower-2030 (Link, period, timestep)
 * CQ-NQ-upper-2031 (Link, period, timestep)
 * CQ-NQ-lower-2031 (Link, period, timestep)
 * CQ-NQ-upper-2032 (Link, period, timestep)
 * CQ-NQ-lower-2032 (Link, period, timestep)
 * CQ-GG-upper-2025 (Link, period, timestep)
 * CQ-GG-lower-2025 (Link, period, timestep)
 * CQ-GG-upper-2026 (Link, period, timestep)
 * CQ-GG-lower-2026 (Link, period, timestep)
 * CQ-GG-upper-2027 (Link, period, timestep)
 * CQ-GG-lower-2027 (Link, period, timestep)
 * CQ-GG-upper-2028 (Link, period, timestep)
 * CQ-GG-lower-2028 (Link, period, timestep)
 * CQ-GG-upper-2029 (Link, period, timestep)
 * CQ-GG-lower-2029 (Link, period, timestep)
 * CQ-GG-upper-2030 (Link, period, timestep)
 * CQ-GG-lower-2030 (Link, period, timestep)
 * CQ-GG-upper-2031 (Link, period, timestep)
 * CQ-GG-lower-2031 (Link, period, timestep)
 * CQ-GG-upper-2032 (Link, period, timestep)
 * CQ-GG-lower-2032 (Link, period, timestep)
 * SQ-CQ-upper-2025 (Link, period, timestep)
 * SQ-CQ-lower-2025 (Link, period, timestep)
 * SQ-CQ-upper-2026 (Link, period, timestep)
 * SQ-CQ-lower-2026 (Link, period, timestep)
 * SQ-CQ-upper-2027 (Link, period, timestep)
 * SQ-CQ-lower-2027 (Link, period, timestep)
 * SQ-CQ-upper-2028 (Link, period, timestep)
 * SQ-CQ-lower-2028 (Link, period, timestep)
 * SQ-CQ-upper-2029 (Link, period, timestep)
 * SQ-CQ-lower-2029 (Link, period, timestep)
 * SQ-CQ-upper-2030 (Link, period, timestep)
 * SQ-CQ-lower-2030 (Link, period, timestep)
 * SQ-CQ-upper-2031 (Link, period, timestep)
 * SQ-CQ-lower-2031 (Link, period, timestep)
 * SQ-CQ-upper-2032 (Link, period, timestep)
 * SQ-CQ-lower-2032 (Link, period, timestep)
 * NNSW-SQ QNI-upper-2025 (Link, period, timestep)
 * NNSW-SQ QNI-lower-2025 (Link, period, timestep)
 * NNSW-SQ QNI-upper-2026 (Link, period, timestep)
 * NNSW-SQ QNI-lower-2026 (Link, period, timestep)
 * NNSW-SQ QNI-upper-2027 (Link, period, timestep)
 * NNSW-SQ QNI-lower-2027 (Link, period, timestep)
 * NNSW-SQ QNI-upper-2028 (Link, period, timestep)
 * NNSW-SQ QNI-lower-2028 (Link, period, timestep)
 * NNSW-SQ QNI-upper-2029 (Link, period, timestep)
 * NNSW-SQ QNI-lower-2029 (Link, period, timestep)
 * NNSW-SQ QNI-upper-2030 (Link, period, timestep)
 * NNSW-SQ QNI-lower-2030 (Link, period, timestep)
 * NNSW-SQ QNI-upper-2031 (Link, period, timestep)
 * NNSW-SQ QNI-lower-2031 (Link, period, timestep)
 * NNSW-SQ QNI-upper-2032 (Link, period, timestep)
 * NNSW-SQ QNI-lower-2032 (Link, period, timestep)
 * CNSW–NNSW QNI-upper-2025 (Link, period, timestep)
 * CNSW–NNSW QNI-lower-2025 (Link, period, timestep)
 * CNSW–NNSW QNI-upper-2026 (Link, period, timestep)
 * CNSW–NNSW QNI-lower-2026 (Link, period, timestep)
 * CNSW–NNSW QNI-upper-2027 (Link, period, timestep)
 * CNSW–NNSW QNI-lower-2027 (Link, period, timestep)
 * CNSW–NNSW QNI-upper-2028 (Link, period, timestep)
 * CNSW–NNSW QNI-lower-2028 (Link, period, timestep)
 * CNSW–NNSW QNI-upper-2029 (Link, period, timestep)
 * CNSW–NNSW QNI-lower-2029 (Link, period, timestep)
 * CNSW–NNSW QNI-upper-2030 (Link, period, timestep)
 * CNSW–NNSW QNI-lower-2030 (Link, period, timestep)
 * CNSW–NNSW QNI-upper-2031 (Link, period, timestep)
 * CNSW–NNSW QNI-lower-2031 (Link, period, timestep)
 * CNSW–NNSW QNI-upper-2032 (Link, period, timestep)
 * CNSW–NNSW QNI-lower-2032 (Link, period, timestep)
 * CNSW­–SNW North-upper-2025 (Link, period, timestep)
 * CNSW­–SNW North-upper-2026 (Link, period, timestep)
 * CNSW­–SNW North-upper-2027 (Link, period, timestep)
 * CNSW­–SNW North-upper-2028 (Link, period, timestep)
 * CNSW­–SNW North-upper-2029 (Link, period, timestep)
 * CNSW­–SNW North-upper-2030 (Link, period, timestep)
 * CNSW­–SNW North-upper-2031 (Link, period, timestep)
 * CNSW­–SNW North-upper-2032 (Link, period, timestep)
 * CNSW–SNW South-upper-2025 (Link, period, timestep)
 * CNSW–SNW South-upper-2026 (Link, period, timestep)
 * CNSW–SNW South-upper-2027 (Link, period, timestep)
 * CNSW–SNW South-upper-2028 (Link, period, timestep)
 * CNSW–SNW South-upper-2029 (Link, period, timestep)
 * CNSW–SNW South-upper-2030 (Link, period, timestep)
 * CNSW–SNW South-upper-2031 (Link, period, timestep)
 * CNSW–SNW South-upper-2032 (Link, period, timestep)
 * VIC–SNSW VNI-upper-2025 (Link, period, timestep)
 * VIC–SNSW VNI-lower-2025 (Link, period, timestep)
 * VIC–SNSW VNI-upper-2026 (Link, period, timestep)
 * VIC–SNSW VNI-lower-2026 (Link, period, timestep)
 * VIC–SNSW VNI-upper-2027 (Link, period, timestep)
 * VIC–SNSW VNI-lower-2027 (Link, period, timestep)
 * VIC–SNSW VNI-upper-2028 (Link, period, timestep)
 * VIC–SNSW VNI-lower-2028 (Link, period, timestep)
 * VIC–SNSW VNI-upper-2029 (Link, period, timestep)
 * VIC–SNSW VNI-lower-2029 (Link, period, timestep)
 * VIC–SNSW VNI-upper-2030 (Link, period, timestep)
 * VIC–SNSW VNI-lower-2030 (Link, period, timestep)
 * VIC–SNSW VNI-upper-2031 (Link, period, timestep)
 * VIC–SNSW VNI-lower-2031 (Link, period, timestep)
 * VIC–SNSW VNI-upper-2032 (Link, period, timestep)
 * VIC–SNSW VNI-lower-2032 (Link, period, timestep)
 * VIC-SESA Heywood-upper-2025 (Link, period, timestep)
 * VIC-SESA Heywood-lower-2025 (Link, period, timestep)
 * VIC-SESA Heywood-upper-2026 (Link, period, timestep)
 * VIC-SESA Heywood-lower-2026 (Link, period, timestep)
 * VIC-SESA Heywood-upper-2027 (Link, period, timestep)
 * VIC-SESA Heywood-lower-2027 (Link, period, timestep)
 * VIC-SESA Heywood-upper-2028 (Link, period, timestep)
 * VIC-SESA Heywood-lower-2028 (Link, period, timestep)
 * VIC-SESA Heywood-upper-2029 (Link, period, timestep)
 * VIC-SESA Heywood-lower-2029 (Link, period, timestep)
 * VIC-SESA Heywood-upper-2030 (Link, period, timestep)
 * VIC-SESA Heywood-lower-2030 (Link, period, timestep)
 * VIC-SESA Heywood-upper-2031 (Link, period, timestep)
 * VIC-SESA Heywood-lower-2031 (Link, period, timestep)
 * VIC-SESA Heywood-upper-2032 (Link, period, timestep)
 * VIC-SESA Heywood-lower-2032 (Link, period, timestep)
 * SESA-CSA-upper-2025 (Link, period, timestep)
 * SESA-CSA-lower-2025 (Link, period, timestep)
 * SESA-CSA-upper-2026 (Link, period, timestep)
 * SESA-CSA-lower-2026 (Link, period, timestep)
 * SESA-CSA-upper-2027 (Link, period, timestep)
 * SESA-CSA-lower-2027 (Link, period, timestep)
 * SESA-CSA-upper-2028 (Link, period, timestep)
 * SESA-CSA-lower-2028 (Link, period, timestep)
 * SESA-CSA-upper-2029 (Link, period, timestep)
 * SESA-CSA-lower-2029 (Link, period, timestep)
 * SESA-CSA-upper-2030 (Link, period, timestep)
 * SESA-CSA-lower-2030 (Link, period, timestep)
 * SESA-CSA-upper-2031 (Link, period, timestep)
 * SESA-CSA-lower-2031 (Link, period, timestep)
 * SESA-CSA-upper-2032 (Link, period, timestep)
 * SESA-CSA-lower-2032 (Link, period, timestep)

# REZ Hosting

### Initial Limits

In [ ]:
df = pd.read_csv("../isp_sheets_23/network_capability/rez_limits.csv")

# will have to be seasonal rating to get units

# once this is done do hydro

# then run sc and pc as SSLT with load blocks

# then add policy constraints -> installed cap coefficients

# otherwise normal net export constraints

gens = pd.read_csv("gen_names.csv")

# filter gens by rez group / fuel

# q6_var = sum([n.model.variables["Generator-p_nom"][gen] for gen in ...)

### Augmentations

### Groups

In [24]:
# Grab REZ info

# filter by gens then ex. Q6 = REZ + thingo

import requests

def get_lat_lon(place, api_key):
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {
        "address": place,
        "key": api_key
    }
    response = requests.get(base_url, params=params)
    data = response.json()

    if data["status"] == "OK":
        location = data["results"][0]["geometry"]["location"]
        return location["lat"], location["lng"]
    else:
        raise Exception(f"Error from API: {data['status']}")

# Example usage
API_KEY = "AIzaSyA3s4v5a5cnyHSzojQD2_glzzmYxyMBiSI"
# lat, lon = get_lat_lon("Avonlie Solar Farm" + " Australia", API_KEY)
# print(f"Gundagai NSW coordinates: {lat}, {lon}")

In [ ]:
import geopandas as gpd
from shapely.geometry import Point
from collections import defaultdict as dd

def check_point_in_rez(lat, lon, rez_gdf):
    """
    Check if (lat, lon) point lies inside any REZ polygon
    """
    point = Point(lon, lat)  # shapely uses (x=lon, y=lat)
    
    matches = rez_gdf[rez_gdf.geometry.contains(point)]
    if matches.empty:
        # print(f"Point ({lat}, {lon}) is NOT inside any REZ zone.")

        return None
    else:
        # print(f"Point ({lat}, {lon}) IS inside the following REZ zone(s):")

        rez = matches['Name'].values[0].split(" ")
        # print(rez)

        return rez[0]

# Path to your AEMO KMZ file
# KMZ_FILE = "aemo-indicative-rez-boundaries-2025-gis-data.kmz"
# rez_gdf = load_rez_from_kmz(KMZ_FILE)
KML_FILE = "../data/indicative-rez-boundaries-2024-gis-data.kml"
rez_gdf = gpd.read_file(KML_FILE, driver='KML')

gen_rez_map = dd(dict)

df = pd.read_csv("../isp_sheets_23/summary_mapping/existing.csv")

for _,row in df.iterrows():

    # materially affects REZ transmission if VERY large (maybe not coal or gas or hydro if that's baseline?)

    # check PLEXOS

    gen = row["Existing generator"]

    fuel = row["Fuel type"]

    gen_lat,gen_lon = get_lat_lon(gen + " Australia", API_KEY)

    rez = check_point_in_rez(gen_lat, gen_lon, rez_gdf)

    if rez != None:
        print(rez)
        gen_rez_map[gen]["REZ"] = rez
        gen_rez_map[gen]["Fuel"] = fuel

N9
N9
Q6
Q6
Q6
Q8
Q8
Q6
Q8
Q8
V5
V5
N12
Q8
Q3
Q6
S1
T1
N9
N6
Q5
Q8
Q8
S3
S3
S8
T1
T1
V4
S3
N7
N7
N7
N7
Q1
Q1
T2
T3
T2
T2
T3
T2
T3

Exception: Error from API: OVER_QUERY_LIMIT

In [36]:
gen_rez_map

defaultdict(dict,
            {'Eraring': {'REZ': 'N9', 'Fuel': 'Black Coal'},
             'Vales Point B': {'REZ': 'N9', 'Fuel': 'Black Coal'},
             'Callide B': {'REZ': 'Q6', 'Fuel': 'Black Coal'},
             'Callide C': {'REZ': 'Q6', 'Fuel': 'Black Coal'},
             'Gladstone': {'REZ': 'Q6', 'Fuel': 'Black Coal'},
             'Kogan Creek': {'REZ': 'Q8', 'Fuel': 'Black Coal'},
             'Millmerran': {'REZ': 'Q8', 'Fuel': 'Black Coal'},
             'Stanwell': {'REZ': 'Q6', 'Fuel': 'Black Coal'},
             'Tarong': {'REZ': 'Q8', 'Fuel': 'Black Coal'},
             'Tarong North': {'REZ': 'Q8', 'Fuel': 'Black Coal'},
             'Loy Yang A Power Station': {'REZ': 'V5', 'Fuel': 'Brown Coal'},
             'Loy Yang B': {'REZ': 'V5', 'Fuel': 'Brown Coal'},
             'Tallawarra': {'REZ': 'N12', 'Fuel': 'Gas'},
             'Condamine A': {'REZ': 'Q8', 'Fuel': 'Gas'},
             'Townsville Power Station': {'REZ': 'Q3', 'Fuel': 'Gas'},
             'Yarwun Cogen': {'REZ': 'Q6', 'Fuel': 'Gas'},
             'Pelican Point': {'REZ': 'S1', 'Fuel': 'Gas'},
             'Tamar Valley Combined Cycle': {'REZ': 'T1', 'Fuel': 'Gas'},
             'Colongra': {'REZ': 'N9', 'Fuel': 'Gas'},
             'Uranquinty': {'REZ': 'N6', 'Fuel': 'Gas'},
             'Barcaldine Power Station': {'REZ': 'Q5', 'Fuel': 'Gas'},
             'Braemar 2 Power Station': {'REZ': 'Q8', 'Fuel': 'Gas'},
             'Oakey Power Station': {'REZ': 'Q8', 'Fuel': 'Gas'},
             'Hallett GT': {'REZ': 'S3', 'Fuel': 'Gas'},
             'Mintaro GT': {'REZ': 'S3', 'Fuel': 'Gas'},
             'Port Lincoln GT': {'REZ': 'S8', 'Fuel': 'Liquid Fuel'},
             'Bell Bay Three': {'REZ': 'T1', 'Fuel': 'Gas'},
             'Tamar Valley Peaking': {'REZ': 'T1', 'Fuel': 'Gas'},
             'Mortlake': {'REZ': 'V4', 'Fuel': 'Gas'},
             'Angaston': {'REZ': 'S3', 'Fuel': 'Liquid Fuel'},
             'Blowering': {'REZ': 'N7', 'Fuel': 'Water'},
             'Guthega': {'REZ': 'N7', 'Fuel': 'Water'},
             'Tumut 3': {'REZ': 'N7', 'Fuel': 'Water'},
             'Upper Tumut': {'REZ': 'N7', 'Fuel': 'Water'},
             'Barron Gorge': {'REZ': 'Q1', 'Fuel': 'Water'},
             'Kareeya': {'REZ': 'Q1', 'Fuel': 'Water'},
             'Wivenhoe': {'REZ': 'T2', 'Fuel': 'Water'},
             'Catagunya / Liapootah / Wayatinah': {'REZ': 'T3',
              'Fuel': 'Water'},
             'Cethana': {'REZ': 'T2', 'Fuel': 'Water'},
             'Devils Gate': {'REZ': 'T2', 'Fuel': 'Water'},
             'Lake Echo': {'REZ': 'T3', 'Fuel': 'Water'},
             'Lemonthyme / Wilmot': {'REZ': 'T2', 'Fuel': 'Water'},
             'Poatina': {'REZ': 'T3', 'Fuel': 'Water'}})

In [39]:
df = pd.read_csv("../isp_sheets_23/REZ/rez_summary.csv")

rez_map = df.set_index("Name")["ID"].to_dict()

df = pd.read_csv("../isp_sheets_23/summary_mapping/existing.csv")


df["REZ"] = df["REZ location"].map(rez_map)

In [40]:
df

,Existing generator,Technology type,Region,Sub-region,REZ location,Status,Regional build cost zone,Fuel type,Fuel cost mapping,Summer rating (MW),...,Mean time to repair - Partial outage Post 2022,Maintenance duration (%),Minimum load (MW),Maximum capacity factor (%),FOM ($/kW/annum),VOM ($/MWh sent-out),Heat rate,MLF,Auxiliary load (%),REZ
0,Bayswater,Steam Sub Critical,NSW,CNSW,NaN,Existing,NaN,Black Coal,Bayswater,Bayswater,...,Black Coal NSW,Black Coal,BW01,NSW Coal,Bayswater,Bayswater,Bayswater,Bayswater,Black Coal NSW,NaN
1,Eraring,Steam Sub Critical,NSW,SNW,NaN,Existing,NaN,Black Coal,Eraring,Eraring,...,Black Coal NSW,Black Coal,ER01,NSW Coal,Eraring,Eraring,Eraring,Eraring,Black Coal NSW,NaN
2,Mt Piper,Steam Sub Critical,NSW,CNSW,NaN,Existing,NaN,Black Coal,Mt Piper,Mt Piper,...,Black Coal NSW,Black Coal,MP1,NSW Coal,Mt Piper,Mt Piper,Mt Piper,Mt Piper,Black Coal NSW,NaN
3,Vales Point B,Steam Sub Critical,NSW,SNW,NaN,Existing,NaN,Black Coal,Vales Point B,Vales Point B,...,Black Coal NSW,Black Coal,VP5,NSW Coal,Vales Point B,Vales Point B,Vales Point B,Vales Point B,Black Coal NSW,NaN
4,Callide B,Steam Sub Critical,QLD,CQ,NaN,Existing,NaN,Black Coal,Callide B,Callide B,...,Black Coal QLD,Black Coal,CALL_B_1,NaN,Callide B,Callide B,Callide B,Callide B,Black Coal QLD,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,Stockyard Hill Wind Farm,Wind,VIC,VIC,South West Victoria,Existing,NaN,Wind,Wind,Stockyard Hill Wind Farm,...,Wind,Wind,NaN,NaN,All Wind,All Wind,NaN,Stockyard Hill Wind Farm,Wind,V4
248,Waubra Wind Farm,Wind,VIC,VIC,Western Victoria,Existing,NaN,Wind,Wind,Waubra Wind Farm,...,Wind,Wind,NaN,NaN,All Wind,All Wind,NaN,Waubra Wind Farm,Wind,V3
249,Yaloak South Wind Farm,Wind,VIC,VIC,Western Victoria,Existing,NaN,Wind,Wind,Yaloak South Wind Farm,...,Wind,Wind,NaN,NaN,All Wind,All Wind,NaN,Yaloak South Wind Farm,Wind,V3
250,Yambuk Wind Farm,Wind,VIC,VIC,South West Victoria,Existing,NaN,Wind,Wind,Yambuk Wind Farm,...,Wind,Wind,NaN,NaN,All Wind,All Wind,NaN,Yambuk Wind Farm,Wind,V4
251,Yendon Wind Farm,Wind,VIC,VIC,Western Victoria,Existing,NaN,Wind,Wind,Yendon Wind Farm,...,Wind,Wind,NaN,NaN,All Wind,All Wind,NaN,Yendon Wind Farm,Wind,V3